# Generated by Django 4.1.7 on 2023-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_countryprod_order_productmanager_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='newornot',
            new_name='new_or_not',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
