# Generated by Django 4.1.7 on 2023-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allprice',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
