# Generated by Django 4.1.7 on 2023-03-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_alter_order_allprice_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
